export const defaults = {
  wallHeight: 96,
  studSpacing: 16,
  wallType: 'wood',
  roomWidth: 120,
  roomLength: 120,
  drywallThickness: 0.5,
  insulation: 'batt',
  electrical: { outlets: 4, switches: 2 },
  plumbing: { fixtures: [] as any[] },
  ceilingHeight: 2.7,
  units: 'metric',
  hasHvac: false,
  doorWidth: 36,
  doorHeight: 80,
  windowWidth: 48,
  windowHeight: 36,
  flooring: 'vinyl',
  paintColor: '#ffffff',
}
